### ISSUE TITLE
The code doesn't work

### ISSUE THREAD

**Issue by frostant** [MorvanZhou/easy-scraping-tutorial#5]
In the code of requests.post().
I don't why you code can only print('Hello there,  !')  even change Chinese into English.

```
data = {'firstname': '莫烦', 'lastname': '周'}
r = requests.post('http://pythonscraping.com/files/processing.php', data=data)
print(r.text)
# Hello there, 莫烦 周!
```
Best Wish!

**Comment by zhiyongLiu1114** [comment]
try this url 
http://pythonscraping.com/pages/files/processing.php
the code on github is not correct
